#task_instructions:
#- ""
#multi_choice_example_format:
#- "{}
#
#{}
#
#Answer with the option's letter from the given choices directly."
#
#short_ans_example_format:
#- "{}
#
#Answer the question using a single word or phrase."
#temperature:
#- 0
task_instructions:
- ""
multi_choice_example_format:
- "Hint: Please answer the question and provide the correct option letter, e.g., A, B, C, D, at the end.

{}

{}"

short_ans_example_format:
- "Hint: Please answer the question and provide the final answer at the end.

{}"
temperature:
- 0